global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]
  
  - job_name: "ohlcv-agent"
    static_configs:
      - targets: ["localhost:6066"]
    metrics_path: /metrics
  
  - job_name: "anomaly-agent"
    static_configs:
      - targets: ["loclahost:6067"]
    metrics_path: /metrics
  
  - job_name: "sentiment-agent"
    static_configs:
      - targets: ["localhost:6068"]
    metrics_path: /metrics
  
  - job_name: "dlq-agent"
    static_configs:
      - targets: ["localhost:6069"]
    metrics_path: /metrics
  
  - job_name: "fastapi"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: /metrics
  
  - job_name: "timescaledb"
    static_configs:
      - targets: ["localhost:9187"]
    metrics_path: /metrics